#!/usr/bin/env bash
# Script that adds custom header to nginx
sudo apt-get -y update
sudo apt-get -y install nginx

new_header="\t\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "42i\ $new_header" /etc/nginx/sites-available/default

sudo service nginx restart
