#!/usr/bin/env bash
# setting up a load balancer
sudo add-apt-repository ppa:vbernat/haproxy-1.7 -y
sudo apt-get update
sudo apt install -y haproxy

FRONT="\\\nfrontend http_front\n\tbind *:80\
     	    \n\tmode http\n\tdefault_backend http_back"
BACK="\\nbackend http_back\n\tbalance roundrobin\
	    \n\tserver 328-web-01 35.185.90.17:80 check\
	    \n\tserver 328-web-02 35.196.3.9:80 check"
sudo sed -i "\$a$FRONT$BACK" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
