#!/usr/bin/env bash
# Displays `Holberton School` 10 times and `Hi` on 9th iteration

i=1
while (( i<=20 )); do
	case $i in
		4)  echo "bad luck from China" ;;
		9)  echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
		*)  echo "$i"
	esac

	i=$((i+1))
done
