#!/usr/bin/env bash
# This script installs nginx & and configures to output 'Holberton School' by default

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
