#!/usr/bin/env bash
# Configures the ip address to point to the certain addresses

cp /etc/hosts ~/hosts.temp
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.temp
sed -ie '3i8.8.8.8     facebook\.com' ~/hosts.temp
cp -f ~/hosts.temp /etc/hosts
